### ISSUE TITLE
Add learning resources to README file

### ISSUE THREAD

**Issue by saurabhnative** [saurabhnative/react30_14_charts_data#2]
Add learning resources in README.md file related to displaying charts in react.js from data fetched using API.
Any links to youtube tutorials, official docs or articles from Medium, Dev.to or Hashnode are preferred.
Multiple contributors are allowed for this issue.

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by saurabhnative** [comment]
@beertocode You have been added as an assignee. Feel free to submit pull request to this repository.

**Comment by shobhi1310** [comment]
Can I contribute to this as well ?

**Comment by lapohjan** [comment]
I would like to help with this.

**Comment by saurabhnative** [comment]
@shobhi1310 Sure...You are added to assignee list. Feel free to submit pull request to this repository.

**Comment by lapohjan** [comment]
I would like to contribute.

**Comment by C-Lion** [comment]
Hi, I see several people asked to be assigned to this but it seems to also indicate the more the merrier. 
1. Do I need to be assigned to contribute via PR? 
2. Where/how to add the info? 
I see the README.md file already has what seems to be a tutorial (react30_14_charts_display).
Do you just want a table with Title/Description/Links etc added to the bottom of that page?
Is there somewhere else to add these links to that I missed? Thanks

**Comment by saurabhnative** [comment]
@C-Lion This is a collection of projects in which we are adding learning resources to help new developers.
If you look at another project in the series here: [video player](https://github.com/codeclassifiers/react30_13_video_player)
There is a learning resources section added by contributors with relevant links in between **Learnings** and **Demo** section.
We need to add similar learning resources here in Markdown syntax which are related to displaying charts in react.js from data fetched using API.
Articles from Medium, Dev.to, Hashnode or Youtube are preferred.
You have been added as an assignee. Feel free to submit PR to this project.
